workflows:
  ios-release:
    name: iOS Release IPA Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Clean iOS folders
        script: |
          rm -rf ios/Pods
          rm -rf ios/Podfile.lock
          rm -rf ios/.symlinks
          rm -rf ios/Flutter/Flutter.framework
          rm -rf ios/Flutter/Flutter.podspec
          rm -rf build/ios

      - name: Install CocoaPods
        script: |
          cd ios
          pod repo update
          pod install --repo-update
          cd ..

      - name: Build iOS archive (no signing)
        script: |
          flutter build ios --release --no-codesign

      - name: Create ExportOptions.plist (auto)
        script: |
          cat <<EOF > ExportOptions.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>ad-hoc</string>
              <key>compileBitcode</key>
              <false/>
              <key>destination</key>
              <string>export</string>
              <key>stripSwiftSymbols</key>
              <true/>
          </dict>
          </plist>
          EOF

      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath build/ios/archive/Runner.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath build/ios/ipa

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive

    publishing:
      email:
        recipients:
          - "ahsanulalam.500@gmail.com"
