workflows:
  ios-release:
    name: iOS Release IPA Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Clean iOS folders
        script: |
          rm -rf ios/Pods
          rm -rf ios/Podfile.lock
          rm -rf build/ios

      - name: Install CocoaPods
        script: |
          cd ios
          pod repo update
          pod install --repo-update
          cd ..

      - name: Build Xcode archive (Codemagic CLI)
        script: |
          xcode-project build-archive \
            --project ios/Runner.xcodeproj \
            --scheme Runner \
            --archive-path build/ios/archive/Runner.xcarchive

      - name: Build IPA (Codemagic CLI)
        script: |
          xcode-project build-ipa \
            --archive-path build/ios/archive/Runner.xcarchive \
            --output build/ios/ipa

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
