workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter Packages
        script: |
          flutter pub get

      - name: Update CocoaPods Repo
        script: |
          cd ios
          pod repo update
          cd ..

      - name: Build iOS (No Codesign)
        script: |
          flutter build ipa --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - "ahsanulalam.500@gmail.com"
