workflows:
  ios-release:
    name: Build iOS IPA (No Sign Patch)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Flutter pub get
        script: flutter pub get

      - name: Clean iOS build
        script: |
          rm -rf ios/Pods
          rm -rf ios/Podfile.lock
          rm -rf build/ios

      - name: Install Pods
        script: |
          cd ios
          pod repo update
          pod install --repo-update
          cd ..

      - name: Build Flutter iOS (no codesign)
        script: flutter build ios --release --no-codesign

      - name: Archive with dummy team
        script: |
          xcodebuild -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -archivePath build/ios/archive/Runner.xcarchive \
            archive \
            DEVELOPMENT_TEAM="0000000000" \
            CODE_SIGN_STYLE="Manual" \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY=""

      - name: Create ExportOptions.plist (patched)
        script: |
          cat <<EOF > ExportOptions.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>release-testing</string>
              <key>signingStyle</key>
              <string>manual</string>
              <key>teamID</key>
              <string>0000000000</string>
              <key>stripSwiftSymbols</key>
              <true/>
              <key>destination</key>
              <string>export</string>
          </dict>
          </plist>
          EOF

      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath build/ios/archive/Runner.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath build/ios/ipa

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
