workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter Packages
        script: |
          flutter pub get

      - name: Clean iOS Pods & Cache
        script: |
          rm -rf ios/Pods
          rm -rf ios/Podfile.lock
          rm -rf ios/.symlinks
          rm -rf ios/Flutter/Flutter.framework
          rm -rf ios/Flutter/Flutter.podspec

      - name: Update CocoaPods Repo (Fix Firebase version conflict)
        script: |
          cd ios
          pod repo update
          cd ..

      - name: Install iOS Pods Fresh
        script: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Build iOS IPA (No Codesign)
        script: |
          flutter build ipa --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - "ahsanulalam.500@gmail.com"
